# online
<Location "/account">
  ProxyPass "http://localhost:39600/account"
  ProxyPassReverse "http://localhost:39600/account"
</Location>
<Location "/api">
  ProxyPass "http://localhost:39600/api"
  ProxyPassReverse "http://localhost:39600/api"
</Location>
ProxyPass "/product-key" "http://localhost:39600/product-key"
ProxyPassReverse "/product-key" "http://localhost:39600/product-key"

# goobo
ProxyPass "/goobo" "http://localhost:39600/goobo"
ProxyPassReverse "/goobo" "http://localhost:39600/goobo"
ProxyPass "/anacostia" "ws://localhost:39600/anacostia"
ProxyPassReverse "/anacostia" "ws://localhost:39600/anacostia"

# punch  
ProxyPass "/punch" "http://localhost:39600/punch"
ProxyPassReverse "/punch" "http://localhost:39600/punch"
ProxyPass "/ip" "http://localhost:39600/ip"
ProxyPassReverse "/ip" "http://localhost:39600/ip"
ProxyPass "/wss" "ws://localhost:39600/wss"
ProxyPassReverse "/wss" "ws://localhost:39600/wss"

# voice chat
<Location "/livekit">
  ProxyPass "http://localhost:39600/livekit"
  ProxyPassReverse "http://localhost:39600/livekit"
</Location>

#Alias /chat /httpd/chat
#<Directory /httpd/chat>
#  AllowOverride none
#  Require all granted
#  FallbackResource /httpd/chat/index.html
#</Directory>

<Location "/online">
  ProxyPass "http://localhost:39600/online"
  ProxyPassReverse "http://localhost:39600/online"
</Location>

AddType application/wasm .wasm
