#!/bin/sh
rsync \
  --compress \
  --recursive \
  --include-from="./rsync-include.txt" \
  --exclude-from="./rsync-exclude.txt" \
  --delete \
  -e "ssh -i \"./notkeys/key\"" \
  ./ ubuntu@193.122.154.50:/httpd/online/
ssh -i "./notkeys/key" ubuntu@193.122.154.50 "pm2 restart online > /dev/null"
echo "Done"
